version: "3.9"
services:
  eurofit-db:
    image: postgres
    restart: no
    container_name: noties-app
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
